const appname = "Tralaga";
const appversion = "Version 1.0.0";
const credits = "@Xeplas";
const email = "Email";
const emailHint = "johndoe@email.com";
const password = "Password";
const passwordHint = "********";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "John Doe";
const forgetPassword = "ForgetPassword";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";
//Home strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
//Home screen strings
const searchAnything = "Searching anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dress",
    featuredCategories = "Featured Categories";
